name: mcMMO-Redeem
version: ${project.version}
description: A plugin that allows players to redeem mcMMO levels in any skill.

main: com.me.tft_02.mcmmoredeem.mcMMORedeem
author: TfT_02
softdepend: [mcMMO, Vault]

commands:
    addcredits:
        description: Give a player credits towards mcMMO levels.
        usage: /addcredits <player> <amount>
        permission: mcmmoredeem.commands.addcredits
        permission-message: You do not have permission to create credits.
    takecredits:
        description: Takes credits from a player.
        usage: /takecredits <player> <amount>
        permission: mcmmoredeem.commands.takecredits
        permission-message: You do not have permission to remove credits.
    sendcredits:
        description: Give another player some of your credits towards McMMO levels.
        usage: /sendcredits <player> <amount>
        permission: mcmmoredeem.commands.sendcredits
        permission-message: You do not have permission to send others credits.
    buycredits:
        description: Buy credits.
        usage: /buycredits <amount>
        permission: mcmmoredeem.commands.buycredits
        permission-message: You do not have permission to purchase credits.
    credits:
        description: Shows the amount of credits you have.
        usage: /credits [player]
        permission: mcmmoredeem.commands.credits
        permission-message: You do not have permission to view your credits.
    redeem:
        description: Redeem mcmmo levels from your credits.
        usage: /redeem <skill> <amount>
        permission: mcmmoredeem.commands.redeem
        permission-message: You do not have permission to redeem credits.

permissions:
    mcmmoredeem.commands.buycredits
        default: true
    mcmmoredeem.commands.credits
        default: true
    mcmmoredeem.commands.redeem
        default: true
    mcmmoredeem.commands.sendcredits
        default: true
    mcmmoredeem.commands.takecredits
        default: op
    mcmmoredeem.commands.addcredits
        default: op
